### ISSUE TITLE
🏛️ [CORE] - Add configs for Desktop Environment

### ISSUE THREAD

**Issue by sansugranes** [sansugranes/.dotfiles#4]
## Description
Add configs for Desktop Environment

## Tasks

- [ ] Add config for Window Manager (i3)
- [ ] Add config for Bar (polybar)
- [ ] Add config for Desktop Notifications (dunst)
- [ ] Add config for Terminal Emulator (alacritty)
