### ISSUE TITLE
🏛️ [CORE] - Add configs for Shell Environment

### ISSUE THREAD

**Issue by sansugranes** [sansugranes/.dotfiles#5]
## Description
Add configs for Shell Environment

## Tasks

- [ ] Add config for Shell (bash)
- [x] Add config for Editor (NeoVim)
- [x] Add config for Terminal Multiplexer (tmux)
